name: CI/CD Pipeline - Java Backend

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    # Define environment variables for Docker Hub authentication
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: abhinavkolamulli/task-executor-backend
      IMAGE_TAG: latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 3. Code Build (Maven Package)
        run: mvn -B package -DskipTests # Builds the JAR artifact

      - name: 4. Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 5. Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: . # Build from the current directory
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          file: ./Dockerfile # Use the existing Dockerfile for multi-stage build